require './app/models/comedian'
require './app/models/special'

Comedian.destroy_all

Special.destroy_all

comedian_1 = Comedian.create(name: "Iliza Shlesinger", age: 35, hometown: "Manhattan, NY")
comedian_2 = Comedian.create(name: "Chelsea Peretti", age: 40, hometown: "Contra Costa County, CA")
comedian_3 = Comedian.create(name: "Anjelah Johnson", age: 36, hometown: "Los Angeles, CA")
comedian_4 = Comedian.create(name: "Ali Wong", age: 36, hometown: "San Francisco, CA")
comedian_5 = Comedian.create(name: "Leslie Jones", age: 51, hometown: "Memphis, TN")
comedian_6 = Comedian.create(name: "Sofia Nino de Rivera", age: 37, hometown: "Mexico City, MX")
comedian_7 = Comedian.create(name: "Maria Bamford", age: 48, hometown: "Port Hueneme, CA")
comedian_8 = Comedian.create(name: "Jen Kirkman", age: 44, hometown: "Needham, MA")
comedian_9 = Comedian.create(name: "Cristela Alonzo", age: 39, hometown: "San Juan, TX")
comedian_10 = Comedian.create(name: "Katherine Ryan", age: 35, hometown: "Sarnia, Ontario")
comedian_11 = Comedian.create(name: "Tina Fey", age: 48, hometown: "Upper Darby, PA")
comedian_12 = Comedian.create(name: "Amy Sedaris", age: 57, hometown: "Endicott, NY")

comedian_1.specials.create(name: "War Paint", run_time: 50, image_path: "https://m.media-amazon.com/images/M/MV5BMjI5ODI2MTgyMF5BMl5BanBnXkFtZTgwMDY1NjIwNjM@._V1_SX1777_CR0,0,1777,937_AL_.jpg")
comedian_1.specials.create(name: "Confirmed Kills", run_time: 75, image_path: "https://m.media-amazon.com/images/M/MV5BMTQ5MzMwNjI4NF5BMl5BanBnXkFtZTcwMTU5Mzc2Mw@@._V1_.jpg")
comedian_1.specials.create(name: "Elder Milennial", run_time: 60, image_path: "https://m.media-amazon.com/images/M/MV5BMjE0OTMxODYxNF5BMl5BanBnXkFtZTgwODgxOTE3NDE@._V1_.jpg")
comedian_2.specials.create(name: "All My Exes", run_time: 300, image_path: "https://m.media-amazon.com/images/M/MV5BYzUwZGMwMmUtNTMwNC00YzI5LThlNDAtNzlmNTU3NzY5ZDNjXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_.jpg")
comedian_2.specials.create(name: "One of the Greats", run_time: 60, image_path: "https://m.media-amazon.com/images/M/MV5BMTA2ODc5NzAzNDFeQTJeQWpwZ15BbWU4MDgxNDY0ODYx._V1_UY317_CR13,0,214,317_AL_.jpg")
comedian_3.specials.create(name: "That's How We Do It", run_time: 60, image_path: "https://m.media-amazon.com/images/M/MV5BMTI4MjI3OTYyNF5BMl5BanBnXkFtZTcwMTQzODMyMw@@._V1_UX214_CR0,0,214,317_AL_.jpg")
comedian_4.specials.create(name: "Baby Cobra", run_time: 75, image_path: "https://m.media-amazon.com/images/M/MV5BOGZhZjdlYmEtYmZiYi00Nzg3LTkzYzYtMzg5NzA2ZTg3YzVkXkEyXkFqcGdeQXVyMTEzNjA2NzM@._V1_SY1000_SX1500_AL_.jpg")
comedian_4.specials.create(name: "Hard Knock Wife", run_time: 90, image_path: "https://m.media-amazon.com/images/M/MV5BMTgyMTkxODI5MV5BMl5BanBnXkFtZTgwMTk0MzQwMjE@._V1_UY317_CR20,0,214,317_AL_.jpg")
comedian_5.specials.create(name: "Problem Child", run_time: 60, image_path: "https://m.media-amazon.com/images/M/MV5BMTk4MTgyMDMzM15BMl5BanBnXkFtZTgwODE1NzczMzE@._V1_UY317_CR15,0,214,317_AL_.jpg")
comedian_5.specials.create(name: "Saturday Night Live", run_time: 60, image_path: "https://m.media-amazon.com/images/M/MV5BYmU5NGVhOWMtZGNiMy00NjAwLWIzNmYtNDA3N2ZkNTk2ZGMxXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_.jpg")
comedian_6.specials.create(name: "Expuesta", run_time: "65", image_path: "https://m.media-amazon.com/images/M/MV5BNDk3MTAyYjktZGYyOS00M2YyLTgyYmMtZmIyNmVhNWVmOWU2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg")
comedian_6.specials.create(name: "Seleccion Natural", run_time: 60, image_path: "https://m.media-amazon.com/images/M/MV5BN2ZkMTE4MWItOTc5Ni00ZTMyLWJiNGUtOTJlMWZlNTEzOGM2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg")
comedian_7.specials.create(name: "The Special Special Special", run_time: 75, image_path: "https://m.media-amazon.com/images/M/MV5BMTc5MjE0ODQ4M15BMl5BanBnXkFtZTgwNDQ3MjE2NDM@._V1_SY1000_CR0,0,1429,1000_AL_.jpg")
comedian_7.specials.create(name: "The Burning Bridges Tour", run_time: 90, image_path: "https://m.media-amazon.com/images/M/MV5BMTI4MzQzMjQ3M15BMl5BanBnXkFtZTYwMTU1OTAz._V1_UX214_CR0,0,214,317_AL_.jpg")
comedian_8.specials.create(name: "Hail to the Freaks", run_time: 80, image_path: "https://m.media-amazon.com/images/M/MV5BMzUyMTUxMWItNzBmZi00ZDg3LTk4NzAtYzFlMmI3NjZjZDlhXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_UY317_CR14,0,214,317_AL_.jpg")
comedian_8.specials.create(name: "I'm Gonna Die Alone(And I Feel Fine)", run_time: 95, image_path: "https://m.media-amazon.com/images/M/MV5BYTFiODMzN2EtMDJmZC00NjRiLWI1YTctNWUxZjE0ZDRhZmFjXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg")
comedian_9.specials.create(name: "Muy Caliente Edition 2", run_time: 80, image_path: "https://m.media-amazon.com/images/M/MV5BZGU4NDdjMjMtOGU3Ni00NTcxLWE2OTYtZDlkN2FmZWE3YjU1XkEyXkFqcGdeQXVyMTI5MDczMTE@._V1_UX214_CR0,0,214,317_AL_.jpg")
comedian_9.specials.create(name: "Legally Brown", run_time: 100, image_path: "https://m.media-amazon.com/images/M/MV5BYjVlN2VhMjYtNDlmZS00YWE4LWFlZDUtMzBjZTQzY2Q4NTBmXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_.jpg")
comedian_10.specials.create(name: "In Trouble", run_time: 95, image_path: "https://m.media-amazon.com/images/M/MV5BYTIzYzE0YzUtZWYyOS00NjY1LWFkZWEtYjI2MDhiNDA2NDllXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_UY317_CR6,0,214,317_AL_.jpg")
comedian_10.specials.create(name: "Live at the Apollo", run_time: 85, image_path: "https://m.media-amazon.com/images/M/MV5BMTYxNjIxNDg3OV5BMl5BanBnXkFtZTgwNTg4MjE4NjM@._V1_SX1500_CR0,0,1500,999_AL_.jpg")
comedian_11.specials.create(name: "Saturday Night Live", run_time: 60, image_path: "https://m.media-amazon.com/images/M/MV5BMTU3NzMwMDI2MF5BMl5BanBnXkFtZTcwNDk0MzcyNw@@._V1_UX214_CR0,0,214,317_AL_.jpg")
comedian_11.specials.create(name: "Bossypants", run_time: 70, image_path: "https://m.media-amazon.com/images/M/MV5BMzVlYzJhNGMtNDI1My00MzJjLWI4NmQtNDdmNjhhMDdjYjNkXkEyXkFqcGdeQXVyNTAyNDQ2NjI@._V1_.jpg")
comedian_12.specials.create(name: "Strangers With Candy", run_time: 90, image_path: "https://m.media-amazon.com/images/M/MV5BODIyNDE5NDg2OV5BMl5BanBnXkFtZTcwMDc0NDU5Ng@@._V1_UY317_CR13,0,214,317_AL_.jpg")
comedian_12.specials.create(name: "Bojack Horseman", run_time: 35, image_path: "https://m.media-amazon.com/images/M/MV5BMTU2Njg4NzQ3MV5BMl5BanBnXkFtZTgwNzY5NzA4NjM@._V1_SX1500_CR0,0,1500,999_AL_.jpg")
comedian_12.specials.create(name: "Simple Times", run_time: 55, image_path: "https://m.media-amazon.com/images/M/MV5BMTQ2MzU4NzEyM15BMl5BanBnXkFtZTgwMjI3Njg0ODE@._V1_SY1000_CR0,0,666,1000_AL_.jpg")
